package LogPack;

public class Exception {

	public static void main(String[] args) {
		
		System.out.println("1111111111111111");
		
		try {
			System.out.println(3333/0);
		} catch (ArithmeticException e) {
			System.out.println("test user ");
		}
		
		System.out.println("4444444444444");
		System.out.println("5555555555555");

	}
		

}
